### ISSUE TITLE
Consider changing Python API to one similar to csv from standard library

### ISSUE THREAD

**Issue by sirex** [solidsnack/tsv#1]
Many Python libraries tries to mimic API's from standard Python library, this makes using new libraries much easier, because of familiar API.

TSV format is quite similar to CSV, so `csv` module API can be used for `tsv`.

See: https://docs.python.org/3/library/csv.html

**Comment by solidsnack** [comment]
This seems like a fairly straightforward thing to do. At the very least, we can support `.reader()` and `.writer()`.
