### ISSUE TITLE
missing code when installed with pip

### ISSUE THREAD

**Issue by gbonline** [solidsnack/tsv#11]
Hi' I found that installing this module with pip, the version installed is 1.0 but the 

 `tsv.py` file is missing the code from 
```
class reader .....

class writer .....
```
so your example listed here give me a runtime exception when
try to call the tsv.writer

**Comment by solidsnack** [comment]
Oh. I guess it needs to be re-released.

**Comment by solidsnack** [comment]
Now with CSV compatible API: https://pypi.python.org/pypi/linear-tsv/1.1.0

**Comment by solidsnack** [comment]
Thank you for your bug report.
