### ISSUE TITLE
Forbidden final backslash?

### ISSUE THREAD

**Issue by sirex** [solidsnack/tsv#4]
It is possible to generate a TSV using `tsv.to`, containing backslash in a last field, but not possible to read this output using `tsv.un`.

Also, there is no explanation, why final backslash is forbidden?

**Comment by solidsnack** [comment]
Yeah, I can not remember why it is forbidden.

**Comment by sirex** [comment]
Found it:

> If a single backslash is encountered at the end of a field, it is an error. If a backslash precedes another character but does not form one of the escape sequences above, it is a “superfluous backslash” and is removed from the field on read. Such a “superfluous backslash” must never be written by a conforming implementation.
> 
> http://dataprotocols.org/linear-tsv/#specification

**Comment by solidsnack** [comment]
So `\\` at EOL is okay but `\` is not. Aha.

**Comment by solidsnack** [comment]
Resolved in 0ff9051
