### ISSUE TITLE
Version v1 plans?

### ISSUE THREAD

**Issue by roll** [solidsnack/tsv#7]
Hi!

Thanks for the lib! We use it in https://github.com/frictionlessdata/tabulator-py.

Do you have plans to release v1?

**Comment by solidsnack** [comment]
I can do that pretty soon, sure. Prior to v1 is there anything you'd like to see added?

**Comment by roll** [comment]
Sorry for the late answer. It just works for us. So I can't ask more)

**Comment by solidsnack** [comment]
Okay, by Saturday then.

**Comment by roll** [comment]
@solidsnack 
Cool! May be we could also check with @sirex about v1 thoughts.

**Comment by sirex** [comment]
No thoughts :)

**Comment by solidsnack** [comment]
https://pypi.python.org/pypi/linear-tsv/1.0.0

**Comment by roll** [comment]
@solidsnack 
Awesome! Thanks!
