### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by pmlandwehr** [solidsnack/tsv#8]
Per PyPI, `linear-tsv` is released under the Apache license - but there's no license in the repo! Would you consider adding one?

**Comment by solidsnack** [comment]
I would be happy to add it. If you open a PR, I will merge it.
Peter M. Landwehr <notifications@github.com> schrieb am Fr. 2. Juni 2017 um
12:24:

**Comment by pmlandwehr** [comment]
Please see https://github.com/solidsnack/tsv/pull/9!

**Comment by ashkulz** [comment]
This issue should be closed.
